- name: Irods
  hosts: localhost
  tasks:
    - name: Install software
      package:
        name:
          - irods-icommands 
          - irods-gridftp-client 
          - python3-irodsclient
        