- name: get current kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: current_version

- name: get sha checksum
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/{{current_version.content}}//bin/linux/amd64/kubectl.sha256
    return_content: true
  register: sha_checksum

- name: get current kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/{{current_version.content}}//bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    checksum: "sha256:{{sha_checksum.content}}"
    mode: '0755'

