- name: Add npirelay
  debug:
    msg: "Hello {{user_home.stdout}}"

- name: wsl stuff directory
  file:
    path: "{{user_home.stdout}}/.wsl"
    state: directory
    owner: tud
    group: tud

- name: npirelay binary
  copy:
    dest: "{{user_home.stdout}}/.wsl"
    src: npirelay.exe
    owner: tud
    group: tud