- name: Install socat
  package:
    name:
      - socat

- name: Add npirelay
  debug:
    msg: "Hello {{user_home.stdout}}"

- name: wsl stuff directory
  file:
    path: "{{user_home.stdout}}/.wsl"
    state: directory
    owner: tud
    group: tud

- name: npiperelay binary
  copy:
    dest: "{{user_home.stdout}}/.wsl"
    src: npiperelay.exe
    owner: tud
    group: tud
    mode: preserve

- name: bashrc modification
  blockinfile:
    path: "{{user_home.stdout}}/.bashrc"
    marker: "### {mark} Code for connecting to ssh-agent on windows. Only change when you know stuff"
    block: |
      WSLHOST=${WSL_DISTRO_NAME:-$(uname -n)}
      export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock.$WSLHOST
      ss -a | grep -q $SSH_AUTH_SOCK
      if [ $? -ne 0   ]; then
        rm -f $SSH_AUTH_SOCK
        ( setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"$HOME/.wsl/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork & ) >/dev/null 2>&1
      fi
      